--- #YAML:1.0
name:               Apache2-RequestRec-Time
version:            1.1
abstract:           Bring microseconds to Apache2::RequestRec
author:
    - Jan Pazdziora
license:            Apache License, Version 2.0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
